version: '3.8'

services:
  # BASE DE DATOS ESTUDIANTES
  db-estudiantes:
    image: mysql:8.0
    container_name: netbook_db_estudiantes
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_estudiantes 
    ports:
      - "3307:3306"
    volumes:
      - estudiantes_data:/var/lib/mysql 
  # MICROSERVICIO ESTUDIANTES  
  ms-estudiantes:
    build: .
    container_name: netbook_app_estudiantes
    ports:
      - "5002:5002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-estudiantes:3306/db_estudiantes?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - db-estudiantes

volumes:
  estudiantes_data: 