# ==============================================================================================================================================================================================================
# CONFIGURACIÓN GENERAL DE LA APLICACIÓN (netBOOK - Estudiantes)
# ==============================================================================================================================================================================================================
# Cambiamos el nombre para identificar el microservicio de estudiantes
spring.application.name=netbook-micro-estudiantes

# ===========================================================================================================================
# MANEJO DE ERRORES WEB
# ===========================================================================================================================
# Siempre incluye errores de binding (validación de datos entrantes)
spring.web.error.include-binding-errors=always

# Siempre incluye el mensaje detallado del error
spring.web.error.include-message=always

# ===========================================================================================================================
# CONFIGURACIÓN DE DATASOURCE (CONEXIÓN A BASE DE DATOS)
# ===========================================================================================================================
spring.datasource.url=jdbc:mysql://localhost:3306/netbook_estudiantes?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# Usuario y Contraseña que usas en el ejemplo de Vehículo
spring.datasource.username=root
spring.datasource.password=root

# Driver oficial de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===========================================================================================================================
# CONFIGURACIÓN JPA / HIBERNATE (ORM)
# ===========================================================================================================================
spring.jpa.hibernate.ddl-auto=update

# Muestra y formatea el SQL en consola para ver cómo se crean las tablas de estudiantes
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto optimizado para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===========================================================================================================================
# POOL DE CONEXIONES HIKARICP
# ===========================================================================================================================
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# ===========================================================================================================================
# CONFIGURACIÓN DE RED
# ===========================================================================================================================
server.port=5002